<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/API/DesktopDriver.cs" Link="DesktopDriver.cs" />
    <Compile Include="../../src/Kernel/DesktopKernelRuntime.cs" Link="DesktopKernelRuntime.cs" />
  </ItemGroup>
</Project>
