<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="..\..\src\API\DesktopAppRegistryStore.cs" Link="DesktopAppRegistryStore.cs" />
    <Compile Include="..\..\src\Logic\DesktopViewModels.cs" Link="DesktopViewModels.cs" />
  </ItemGroup>
</Project>
